INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Books', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Computer', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Smarthphone', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Books', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Computer', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Smarthphone', NOW());INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Books', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Computer', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Smarthphone', NOW());INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Books', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Computer', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Smarthphone', NOW());INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Books', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Computer', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Smarthphone', NOW());INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Books', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Computer', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Smarthphone', NOW());INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Books', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Computer', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Smarthphone', NOW());INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Books', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Computer', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Smarthphone', NOW());INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Books', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Computer', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Smarthphone', NOW());INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Books', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Computer', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Smarthphone', NOW());INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Books', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Computer', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Smarthphone', NOW());INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Books', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Computer', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Smarthphone', NOW());INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Books', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Computer', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Smarthphone', NOW());INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Books', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Computer', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('Smarthphone', NOW());